// frontend/src/components/biz/AccountDetailModal.tsx
import { useEffect, useMemo, useState } from 'react';
import { DownloadAuthFile, GetAuthFileModels } from '../../../wailsjs/go/main/App';
import { useI18n } from '../../context/I18nContext';
import type { AuthFile, AuthModel } from '../../types';
import { toErrorMessage } from '../../utils/error';

interface AccountDetailModalProps {
  account: AuthFile;
  onClose: () => void;
}

type DetailField = readonly [string, string];

interface ClickEventLike {
  stopPropagation: () => void;
}

function formatRefreshValue(value: unknown): string {
  if (!value) {
    return '—';
  }
  const date = new Date(value as string | number | Date);
  return Number.isNaN(date.getTime()) ? '—' : date.toLocaleTimeString();
}

function getModelLabel(model: AuthModel): string {
  return model.display_name || model.id || model.name || 'MODEL';
}

export default function AccountDetailModal({ account, onClose }: AccountDetailModalProps) {
  const { t } = useI18n();
  const [models, setModels] = useState<AuthModel[]>([]);
  const [loadingModels, setLoadingModels] = useState(false);
  const [rawContent, setRawContent] = useState('');
  const [loadingRaw, setLoadingRaw] = useState(false);
  const [verifyResult, setVerifyResult] = useState('');
  const [verifying, setVerifying] = useState(false);

  const detailFields = useMemo<DetailField[]>(
    () => [
      [t('common.type'), account.type || '—'],
      [t('accounts.provider'), account.provider || '—'],
      [t('accounts.size'), account.size ? `${account.size} B` : '—'],
      [t('common.status'), account.status || '—'],
      [t('common.enable'), account.disabled ? 'NO' : 'YES'],
      ['REFRESH', formatRefreshValue(account.lastRefresh)],
    ],
    [account, t]
  );

  useEffect(() => {
    let mounted = true;

    async function loadData() {
      setLoadingModels(true);
      try {
        const response = await GetAuthFileModels(account.name);
        if (mounted) {
          setModels(response || []);
        }
      } catch (error) {
        console.error(error);
      } finally {
        if (mounted) {
          setLoadingModels(false);
        }
      }

      setLoadingRaw(true);
      try {
        const response = await DownloadAuthFile(account.name);
        const binary = atob(response.contentBase64);
        let decoded = new TextDecoder().decode(Uint8Array.from(binary, (char) => char.charCodeAt(0)));
        try {
          decoded = JSON.stringify(JSON.parse(decoded), null, 2);
        } catch {
          // Keep the original content if it is not JSON.
        }
        if (mounted) {
          setRawContent(decoded);
        }
      } catch (error) {
        if (mounted) {
          setRawContent(`READ_ERROR: ${toErrorMessage(error)}`);
        }
      } finally {
        if (mounted) {
          setLoadingRaw(false);
        }
      }
    }

    loadData();
    return () => {
      mounted = false;
    };
  }, [account.name]);

  async function verify() {
    setVerifying(true);
    setVerifyResult('VERIFYING...');
    try {
      await GetAuthFileModels(account.name);
      setVerifyResult('✓ VALID');
    } catch (error) {
      console.error(error);
      setVerifyResult('✗ FAILED');
    } finally {
      setVerifying(false);
    }
  }

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-8 backdrop-blur-sm"
      data-collaboration-id="MODAL_ACCOUNT_DETAIL"
      onClick={onClose}
    >
      <div
      className="flex max-h-[90vh] w-full max-w-2xl flex-col border-2 border-[var(--border-color)] bg-[var(--bg-main)] shadow-hard shadow-[var(--shadow-color)]"
        onClick={(event: ClickEventLike) => event.stopPropagation()}
      >
        <header className="flex items-center justify-between border-b-2 border-[var(--border-color)] bg-[var(--bg-main)] px-6 py-4">
          <div className="flex flex-col">
            <div className="text-[9px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)]">
              Object_Inspection
            </div>
            <h3 className="max-w-[450px] truncate text-sm font-black italic uppercase tracking-tighter text-[var(--text-primary)]">
              {account.name}
            </h3>
          </div>
          <button onClick={onClose} className="btn-swiss !p-1 !shadow-none hover:bg-[var(--bg-surface)]">
            <svg className="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="4">
              <path d="M18 6L6 18M6 6l12 12" />
            </svg>
          </button>
        </header>

        <div className="flex-1 space-y-8 overflow-y-auto p-6 selection:bg-[var(--border-color)] selection:text-[var(--bg-main)]">
          <div className="grid grid-cols-3 gap-y-6 border-b-2 border-dashed border-[var(--border-color)] pb-8">
            {detailFields.map(([label, value]) => (
              <div key={label} className="space-y-1">
                <div className="text-[9px] font-black uppercase italic text-[var(--text-muted)]">{label}</div>
                <div className="truncate text-[11px] font-black uppercase text-[var(--text-primary)]">{value}</div>
              </div>
            ))}
          </div>

          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-widest text-[var(--text-muted)]">
                <span className="h-2 w-2 bg-[var(--border-color)]"></span>
                COMPATIBLE_MODELS
              </div>
              {loadingModels ? <span className="animate-pulse text-[9px] font-black">LOADING...</span> : null}
            </div>
            <div className="flex max-h-24 flex-wrap gap-2 overflow-y-auto pr-2">
              {models.length > 0 ? (
                models.map((model, index) => (
                  <span
                    key={`${getModelLabel(model)}-${index}`}
                    className="border border-[var(--border-color)] bg-[var(--bg-surface)] px-2 py-0.5 text-[10px] font-black italic uppercase"
                  >
                    {getModelLabel(model)}
                  </span>
                ))
              ) : !loadingModels ? (
                <div className="text-[10px] font-bold italic text-[var(--text-muted)]">NO_DATA_AVAILABLE</div>
              ) : null}
            </div>
          </section>

          <section className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-widest text-[var(--text-muted)]">
                <span className="h-2 w-2 bg-[var(--border-color)]"></span>
                RAW_SOURCE_DATA
              </div>
              {loadingRaw ? (
                <span className="animate-pulse text-[9px] font-black text-[var(--text-muted)]">FETCHING_FS...</span>
              ) : null}
            </div>
            <div className="max-h-[300px] overflow-auto whitespace-pre border-2 border-[var(--border-color)] bg-[var(--bg-main)] p-4 font-mono text-[10px] leading-relaxed text-[var(--text-primary)] shadow-inner">
              {rawContent}
            </div>
          </section>
        </div>

        <footer className="flex items-center justify-between border-t-2 border-[var(--border-color)] bg-[var(--bg-surface)] px-6 py-4">
          <div className="flex items-center gap-4">
            <button
              onClick={verify}
              disabled={verifying}
              className="btn-swiss bg-[var(--border-color)] !text-[var(--bg-main)]"
            >
              {verifying ? 'VERIFYING...' : 'VERIFY_ACCOUNT'}
            </button>
            {verifyResult ? (
              <span
                className={`text-[10px] font-black italic ${
                  verifyResult.includes('✓') ? 'text-green-600' : 'text-red-600'
                }`}
              >
                {verifyResult}
              </span>
            ) : null}
          </div>
          <button onClick={onClose} className="btn-swiss">
            {t('common.close')}
          </button>
        </footer>
      </div>
    </div>
  );
}

// frontend/src/components/biz/AccountDetailModal.svelte
<script>
  import { createEventDispatcher, onMount } from 'svelte';
  import { t } from '../../lib/i18n';
  import { GetAuthFileModels, DownloadAuthFile } from '../../../wailsjs/go/main/App';

  export let account;
  const dispatch = createEventDispatcher();

  let models = [];
  let loadingModels = false;
  let rawContent = '';
  let loadingRaw = false;
  let verifyResult = '';
  let verifying = false;

  $: DETAIL_FIELDS = [
    [$t('common.type'), account.type || '—'],
    [$t('accounts.provider'), account.provider || '—'],
    [$t('accounts.size'), account.size ? `${account.size} B` : '—'],
    [$t('common.status'), account.status || '—'],
    [$t('common.enable'), account.disabled ? 'NO' : 'YES'],
    ['REFRESH', account.lastRefresh ? new Date(account.lastRefresh).toLocaleTimeString() : '—'],
  ];

  async function loadData() {
    loadingModels = true;
    try {
      const res = await GetAuthFileModels(account.name);
      models = res || [];
    } catch (e) { console.error(e); } finally { loadingModels = false; }

    loadingRaw = true;
    try {
      const res = await DownloadAuthFile(account.name);
      const binary = atob(res.contentBase64);
      rawContent = new TextDecoder().decode(Uint8Array.from(binary, c => c.charCodeAt(0)));
      try { rawContent = JSON.stringify(JSON.parse(rawContent), null, 2); } catch {}
    } catch (e) { rawContent = 'READ_ERROR: ' + e.message; } finally { loadingRaw = false; }
  }

  async function verify() {
    verifying = true;
    verifyResult = 'VERIFYING...';
    try {
      await GetAuthFileModels(account.name);
      verifyResult = '✓ VALID';
    } catch (e) { verifyResult = '✗ FAILED'; } finally { verifying = false; }
  }

  onMount(loadData);
</script>

<!-- Backdrop with Industrial Blur -->
<div class="fixed inset-0 z-50 flex items-center justify-center p-8 bg-black/80 backdrop-blur-sm" on:click={() => dispatch('close')}>
  <div 
    class="bg-[var(--bg-main)] border-2 border-[var(--border-color)] w-full max-w-2xl max-h-[90vh] flex flex-col shadow-hard shadow-[var(--shadow-color)]" 
    on:click|stopPropagation
  >
    <!-- Header: Rigid & Bold -->
    <header class="px-6 py-4 border-b-2 border-[var(--border-color)] flex items-center justify-between bg-[var(--bg-main)]">
      <div class="flex flex-col">
        <div class="text-[9px] font-black uppercase tracking-[0.2em] text-[var(--text-muted)]">Object_Inspection</div>
        <h3 class="text-sm font-black italic uppercase tracking-tighter text-[var(--text-primary)] truncate max-w-[450px]">
          {account.name}
        </h3>
      </div>
      <button on:click={() => dispatch('close')} class="btn-swiss !p-1 !shadow-none hover:bg-[var(--bg-surface)]">
        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="4"><path d="M18 6L6 18M6 6l12 12"/></svg>
      </button>
    </header>

    <!-- Body: Data Intensive Grid -->
    <div class="flex-1 overflow-y-auto p-6 space-y-8 selection:bg-[var(--border-color)] selection:text-[var(--bg-main)]">
      
      <!-- Metrics Grid -->
      <div class="grid grid-cols-3 gap-y-6 border-b-2 border-[var(--border-color)] border-dashed pb-8">
        {#each DETAIL_FIELDS as [label, value]}
          <div class="space-y-1">
            <div class="text-[9px] font-black text-[var(--text-muted)] uppercase italic">{label}</div>
            <div class="text-[11px] font-black text-[var(--text-primary)] uppercase truncate">{value}</div>
          </div>
        {/each}
      </div>

      <!-- Models Section -->
      <section class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="text-[9px] font-black text-[var(--text-muted)] uppercase tracking-widest flex items-center gap-2">
            <span class="w-2 h-2 bg-[var(--border-color)]"></span>
            COMPATIBLE_MODELS
          </div>
          {#if loadingModels}
            <span class="text-[9px] font-black animate-pulse">LOADING...</span>
          {/if}
        </div>
        <div class="flex flex-wrap gap-2 max-h-24 overflow-y-auto pr-2">
          {#if models.length > 0}
            {#each models as model}
              <span class="px-2 py-0.5 border border-[var(--border-color)] text-[10px] font-black italic uppercase bg-[var(--bg-surface)]">
                {model.display_name || model.id || model.name}
              </span>
            {/each}
          {:else if !loadingModels}
            <div class="text-[10px] font-bold text-[var(--text-muted)] italic">NO_DATA_AVAILABLE</div>
          {/if}
        </div>
      </section>

      <!-- Source Content -->
      <section class="space-y-4">
        <div class="flex items-center justify-between">
          <div class="text-[9px] font-black text-[var(--text-muted)] uppercase tracking-widest flex items-center gap-2">
            <span class="w-2 h-2 bg-[var(--border-color)]"></span>
            RAW_SOURCE_DAT
          </div>
          {#if loadingRaw}
            <span class="text-[9px] font-black animate-pulse text-[var(--text-muted)]">FETCHING_FS...</span>
          {/if}
        </div>
        <div class="bg-[var(--bg-main)] border-2 border-[var(--border-color)] p-4 font-mono text-[10px] leading-relaxed text-[var(--text-primary)] overflow-auto max-h-[300px] whitespace-pre shadow-inner">
          {rawContent}
        </div>
      </section>
    </div>

    <!-- Footer: Controlled Action Area -->
    <footer class="px-6 py-4 border-t-2 border-[var(--border-color)] flex items-center justify-between bg-[var(--bg-surface)]">
      <div class="flex items-center gap-4">
        <button 
          on:click={verify}
          disabled={verifying}
          class="btn-swiss bg-[var(--border-color)] !text-[var(--bg-main)]"
        >
          {verifying ? 'VERIFYING...' : 'VERIFY_ACCOUNT'}
        </button>
        {#if verifyResult}
          <span class="text-[10px] font-black italic {verifyResult.includes('✓') ? 'text-green-600' : 'text-red-600'}">
            {verifyResult}
          </span>
        {/if}
      </div>
      <button on:click={() => dispatch('close')} class="btn-swiss">
        {$t('common.close')}
      </button>
    </footer>
  </div>
</div>
