// frontend/src/pages/AccountsPage.svelte
<script>
  import { onMount } from 'svelte';
  import { t } from '../lib/i18n';
  import { ListAuthFiles, SetAuthFileStatus, DeleteAuthFiles } from '../../wailsjs/go/main/App';
  import AccountDetailModal from '../components/biz/AccountDetailModal.svelte';

  export let sidecarStatus;

  let accounts = [];
  let loading = false;
  let searchTerm = '';

  async function loadAccounts() {
    try {
      const res = await ListAuthFiles();
      accounts = res.files || [];
    } catch (e) { 
      console.error(e);
    }
  }

  $: filteredAccounts = accounts.filter(acc => {
    const nameStr = (acc.name || '').toLowerCase();
    const providerStr = (acc.provider || '').toLowerCase();
    const q = searchTerm.toLowerCase();
    return !searchTerm || nameStr.includes(q) || providerStr.includes(q);
  });

  async function toggleStatus(name, disabled) {
    try {
      await SetAuthFileStatus(name, !disabled);
      await loadAccounts();
    } catch (e) { alert('ERROR: ' + e); }
  }

  async function deleteAccount(name) {
    if (!confirm($t('common.confirm_delete'))) return;
    try {
      await DeleteAuthFiles([name]);
      await loadAccounts();
    } catch (e) { 
      alert('DELETE ERROR: ' + e);
    }
  }

  onMount(() => {
    loadAccounts();
  });
</script>

<div class="h-full w-full p-12 overflow-auto bg-[var(--bg-surface)]" data-collaboration-id="PAGE_ACCOUNTS">
  <div class="max-w-6xl mx-auto space-y-8 pb-32">
    <header class="flex items-end justify-between border-b-4 border-[var(--border-color)] pb-4">
      <div>
        <h2 class="text-4xl font-black uppercase italic tracking-tighter text-[var(--text-primary)]">{$t('accounts.title')}</h2>
        <p class="text-[10px] font-bold text-[var(--text-muted)] mt-1 uppercase tracking-widest">{$t('accounts.subtitle')} / {filteredAccounts.length} TOTAL</p>
      </div>
      <button on:click={loadAccounts} class="btn-swiss">{$t('common.refresh')}</button>
    </header>

    <div class="flex flex-wrap gap-6 items-center bg-[var(--bg-main)] border-2 border-[var(--border-color)] p-4 shadow-hard shadow-[var(--shadow-color)]">
      <div class="flex-1 min-w-[300px] flex items-center gap-3">
        <span class="text-[10px] font-black uppercase">{$t('common.search')}:</span>
        <input bind:value={searchTerm} type="text" class="input-swiss flex-1 uppercase" placeholder="NAME / PROVIDER..." />
      </div>
    </div>

    {#if filteredAccounts.length === 0}
      <div class="border-2 border-dashed border-[var(--border-color)] p-20 text-center uppercase font-black italic text-[var(--text-muted)]">
        {$t('accounts.empty')}
      </div>
    {:else}
      <div class="grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 gap-8">
        {#each filteredAccounts as acc (acc.name)}
          <div class="card-swiss bg-[var(--bg-main)] flex flex-col p-6 min-h-[200px]">
            <h3 class="font-black text-sm uppercase break-all mb-4">{acc.name}</h3>
            
            <div class="mt-auto space-y-3">
              <div class="flex justify-between text-[10px] font-bold uppercase border-t border-[var(--border-color)] border-dashed pt-3">
                <span class="text-[var(--text-muted)]">{$t('common.status')}</span>
                <span class={acc.disabled ? 'text-zinc-500' : 'text-green-600'}>{acc.disabled ? 'DIS' : 'ACT'}</span>
              </div>

              <div class="grid grid-cols-2 gap-2">
                <button 
                  on:click={() => selectedAccount = acc}
                  class="btn-swiss !py-1 !text-[9px]"
                >{$t('common.details')}</button>
                <button 
                  on:click={() => deleteAccount(acc.name)}
                  class="btn-swiss !py-1 !text-[9px] !text-red-500"
                >{$t('common.delete')}</button>
              </div>
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

{#if selectedAccount}
  <AccountDetailModal account={selectedAccount} on:close={() => selectedAccount = null} />
{/if}

// frontend/src/pages/AccountsPage.jsx
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useI18n } from '../context/I18nContext.jsx';
import { DeleteAuthFiles, ListAuthFiles } from '../../wailsjs/go/main/App';
import AccountDetailModal from '../components/biz/AccountDetailModal.jsx';

export default function AccountsPage({ sidecarStatus }) {
  const { t } = useI18n();
  const [accounts, setAccounts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedAccount, setSelectedAccount] = useState(null);
  const [pendingDeleteName, setPendingDeleteName] = useState(null);
  const [deleteError, setDeleteError] = useState('');

  const ready = sidecarStatus?.code === 'ready';

  const loadAccounts = useCallback(async () => {
    if (!ready) {
      return;
    }

    setLoading(true);
    try {
      const response = await ListAuthFiles();
      setAccounts(response.files || []);
      setPendingDeleteName(null);
    } catch (error) {
      console.error(error);
    } finally {
      setLoading(false);
    }
  }, [ready]);

  useEffect(() => {
    if (ready) {
      loadAccounts();
    }
  }, [ready, loadAccounts]);

  const filteredAccounts = useMemo(() => {
    const query = searchTerm.toLowerCase();
    return accounts.filter((account) => {
      if (!searchTerm) {
        return true;
      }
      return (
        (account.name || '').toLowerCase().includes(query) ||
        (account.provider || '').toLowerCase().includes(query)
      );
    });
  }, [accounts, searchTerm]);

  async function deleteAccount(name) {
    setDeleteError('');
    try {
      await DeleteAuthFiles([name]);
      setPendingDeleteName(null);
      await loadAccounts();
    } catch (error) {
      console.error(error);
      setDeleteError(`DELETE ERROR: ${error?.message || error}`);
    }
  }

  return (
    <>
      <div
        className="h-full w-full overflow-auto bg-[var(--bg-surface)] p-12"
        data-collaboration-id="PAGE_ACCOUNTS"
      >
        <div className="mx-auto max-w-6xl space-y-8 pb-32">
          <header className="flex items-end justify-between border-b-4 border-[var(--border-color)] pb-4">
            <div>
              <h2 className="text-4xl font-black uppercase italic tracking-tighter text-[var(--text-primary)]">
                {t('accounts.title')}
              </h2>
              <p className="mt-1 text-[10px] font-bold uppercase tracking-widest text-[var(--text-muted)]">
                {t('accounts.subtitle')} / {accounts.length} TOTAL
              </p>
            </div>
            <button onClick={loadAccounts} className="btn-swiss" disabled={!ready || loading}>
              {t('common.refresh')}
            </button>
          </header>

          <div className="flex flex-wrap items-center gap-6 border-2 border-[var(--border-color)] bg-[var(--bg-main)] p-4 shadow-hard shadow-[var(--shadow-color)]">
            <div className="flex min-w-[300px] flex-1 items-center gap-3">
              <span className="text-[10px] font-black uppercase">{t('common.search')}:</span>
              <input
                value={searchTerm}
                onChange={(event) => {
                  setSearchTerm(event.target.value);
                  setPendingDeleteName(null);
                }}
                type="text"
                className="input-swiss flex-1 uppercase"
                placeholder="NAME / PROVIDER..."
              />
            </div>
          </div>

          {deleteError ? (
            <div className="border-2 border-red-500 bg-red-500/10 px-4 py-3 text-[10px] font-black uppercase tracking-wide text-red-500">
              {deleteError}
            </div>
          ) : null}

          {!ready ? (
            <div className="animate-pulse border-2 border-dashed border-[var(--border-color)] p-20 text-center font-black uppercase italic text-[var(--text-muted)]">
              Waiting_for_backend_core...
            </div>
          ) : filteredAccounts.length === 0 ? (
            <div className="border-2 border-dashed border-[var(--border-color)] p-20 text-center font-black uppercase italic text-[var(--text-muted)]">
              {loading ? t('common.loading') : t('accounts.empty')}
            </div>
          ) : (
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2 2xl:grid-cols-3">
              {filteredAccounts.map((account) => (
                <div
                  key={account.name}
                  className="card-swiss flex min-h-[200px] flex-col bg-[var(--bg-main)] p-6 transition-transform hover:translate-x-[-2px] hover:translate-y-[-2px]"
                >
                  <h3 className="mb-4 break-all text-sm font-black uppercase text-[var(--text-primary)]">
                    {account.name}
                  </h3>

                  <div className="mt-auto space-y-3">
                    <div className="flex justify-between border-t border-dashed border-[var(--border-color)] pt-3 text-[10px] font-bold uppercase text-[var(--text-primary)]">
                      <span className="text-[var(--text-muted)]">{t('common.status')}</span>
                      <span className={account.disabled ? 'text-zinc-500' : 'text-green-600'}>
                        {account.disabled ? 'DIS' : 'ACT'}
                      </span>
                    </div>

                    {pendingDeleteName === account.name ? (
                      <div className="space-y-2">
                        <div className="text-[9px] font-black uppercase tracking-wide text-red-500">
                          {t('common.confirm_delete')}
                        </div>
                        <div className="grid grid-cols-2 gap-2">
                          <button
                            onClick={() => setPendingDeleteName(null)}
                            className="btn-swiss !py-1 !text-[9px]"
                          >
                            {t('common.cancel')}
                          </button>
                          <button
                            onClick={() => deleteAccount(account.name)}
                            className="btn-swiss !py-1 !text-[9px] !text-red-500"
                          >
                            {t('common.delete')}
                          </button>
                        </div>
                      </div>
                    ) : (
                      <div className="grid grid-cols-2 gap-2">
                        <button onClick={() => setSelectedAccount(account)} className="btn-swiss !py-1 !text-[9px]">
                          {t('common.details')}
                        </button>
                        <button
                          onClick={() => {
                            setDeleteError('');
                            setPendingDeleteName(account.name);
                          }}
                          className="btn-swiss !py-1 !text-[9px] !text-red-500"
                        >
                          {t('common.delete')}
                        </button>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {selectedAccount ? (
        <AccountDetailModal account={selectedAccount} onClose={() => setSelectedAccount(null)} />
      ) : null}
    </>
  );
}
