// frontend/src/components/ui/SegmentedControl.svelte
<script>
  export let options = []; // [{id, label}]
  export let value;
  
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  function select(id) {
    value = id;
    dispatch('change', id);
  }
</script>

<div class="flex border-2 border-[var(--border-color)] bg-[var(--bg-surface)] w-full max-w-sm">
  {#each options as opt, i}
    <button 
      on:click={() => select(opt.id)}
      class="flex-1 py-1.5 text-[9px] font-black italic transition-all relative
             {i !== options.length - 1 ? 'border-r-2 border-[var(--border-color)]' : ''}
             {value === opt.id 
               ? 'bg-[var(--border-color)] text-[var(--bg-main)]' 
               : 'text-[var(--text-primary)] hover:bg-[var(--bg-main)]/50'}"
    >
      {opt.label}
      {#if value === opt.id}
        <div class="absolute bottom-0 left-0 right-0 h-[3px] bg-[var(--bg-main)]/20"></div>
      {/if}
    </button>
  {/each}
</div>

// frontend/src/components/ui/SegmentedControl.jsx
export default function SegmentedControl({ options, value, onChange }) {
  return (
    <div className="flex w-full max-w-sm border-2 border-[var(--border-color)] bg-[var(--bg-surface)]">
      {options.map((option, index) => (
        <button
          key={option.id}
          onClick={() => onChange(option.id)}
          className={`relative flex-1 py-1.5 text-[9px] font-black italic transition-all ${
            index !== options.length - 1 ? 'border-r-2 border-[var(--border-color)]' : ''
          } ${
            value === option.id
              ? 'bg-[var(--border-color)] text-[var(--bg-main)]'
              : 'text-[var(--text-primary)] hover:bg-[var(--bg-main)]/50'
          }`}
        >
          {option.label}
          {value === option.id ? (
            <div className="absolute bottom-0 left-0 right-0 h-[3px] bg-[var(--bg-main)]/20"></div>
          ) : null}
        </button>
      ))}
    </div>
  );
}
